<?php
// $Id$

function download_count_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
      db_query("CREATE TABLE if not exists {file_downloads} (
        filename varchar(255) character set utf8 NOT NULL,
        count int(11) NOT NULL default '0',
		timestamp int(11) NOT NULL default '0',
		UNIQUE KEY filename (filename)
		) /*!40100 DEFAULT CHARACTER SET utf8 */");
      break;
    case 'pgsql':
	  db_query("CREATE TABLE if not exists {file_downloads} (
        did serial NOT NULL,
        filename character varying(255) NOT NULL,
        count integer DEFAULT 0 NOT NULL,
         \"timestamp\" integer DEFAULT 0 NOT NULL
        )");
       db_query("ALTER TABLE ONLY {file_downloads} ADD CONSTRAINT {file_downloads}_pkey PRIMARY KEY (did)");
	  break;
  }
}