<?php /* $Id$ */
/**
 * @file Download counter
 */ 
 /**
 * Implementation of hook_help()
 */
function download_count_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      // This description is shown in the listing at admin/modules.
      return t('Increments a download counter and logs a descriptive message each time an attached file is downloaded.');
  }
}
/**
 * Implementation of hook_perm()
 */
function download_count_perm() {
  $perms = array();
  $perms[] = 'view all downloads count';
  $perms[] = 'view own nodes downloads count';
  $perms[] = 'view all downloads count in nodes';
  $perms[] = 'view own nodes downloads count in nodes';
  return $perms;
}
/**
 * Implementation of hook_menu()
 */
function download_count_menu($may_cache) {
  $items = array();
  $access = user_access('view all downloads count') || user_access('view own nodes downloads count');

  if ($may_cache) {  
    $items[] = array('path' => 'admin/settings/download_count', 
      'title' => t('download_count'),
      'callback' => 'download_count_admin_page',
      'type' => MENU_NORMAL_ITEM);
	  
    $items[] = array('path' => 'download_counter', 
      'title' => t('download count'),
      'callback' => 'download_count_view_page',
      'access' => $access,
      'type' => MENU_NORMAL_ITEM);
  }
  return $items;
}

function download_count_admin_page() {

  switch (variable_get('file_downloads', FILE_DOWNLOADS_PUBLIC)) {
    case FILE_DOWNLOADS_PUBLIC:
	  $output = '<p>' . t('You are using public download. ') . l(t('Set your download method to private'),'admin/settings') . t(' if you wish for Drupal to keep a record of downloaded files.') . '</p>';
	  break;
	case FILE_DOWNLOADS_PRIVATE:
	  $output = '<p>' . t('You are using the private download method, hence you have the correct setting to allow this module to keep a record of downloaded files.') . '</p>';
	  break;
  }
  
  $output .= download_count_view_page();
  return $output;
  
}

function download_count_view_page() {

  global $user;

  drupal_set_title(t('Download center'));

  $header[] = array('data' => t('filename'), 'field' => 'filename');
  $header[] = array('data' => t('download count'), 'field' => 'count', 'sort' => 'desc');
  $header[] = array('data' => t('last download'), 'field' => 'timestamp');
  
  $rows = array();

  if(user_access('view all downloads count')) {
    $result = db_query("SELECT f.filename, f.count, f.timestamp FROM {file_downloads} f" . tablesort_sql($header));
	}
	else {
	  $result = db_query("SELECT fd.filename, fd.count, fd.timestamp FROM {file_downloads} fd JOIN {files} f ON fd.filename = f.filename JOIN {node} n ON n.nid = f.nid WHERE n.uid = %d" . tablesort_sql($header), $user->uid);
	}
	
  while ($file = db_fetch_object($result)) {
    $row = array();
    $row[] = $file->filename;
	$row[] = $file->count;	
	$row[] = format_interval(time() - $file->timestamp) . ' ago';	
	$rows[] = $row;	
  }

  if (empty($rows)) {
    $rows[] = array(array('data' => t('No file attachment has been downloaded.'), 'colspan' => '3'));
  }

  $output = theme('table', $header, $rows, array('class' => 'download_count'));
  
  return $output;
}

/**
 * Implementation of file_download()
 */
function download_count_file_download($filename) {

  $file = file_create_path($filename);
  $result = db_query("SELECT f.* FROM {files} f WHERE filepath = '%s'", $file);
  if ($file = db_fetch_object($result)) {
    if (user_access('view uploaded files') && node_access('view', node_load($file->nid))) { 
      $message = t('%file was downloaded', array('%file' => theme('placeholder', $filename)));
      watchdog('download', $message, WATCHDOG_NOTICE);		
      // If the file is already added, just increment the count, 
      // otherwise add the file with count 1
      if(db_result(db_query("SELECT filename FROM {file_downloads} WHERE filename = '%s'", $filename))) {
        db_query("UPDATE {file_downloads} SET count = count+1 WHERE filename = '%s'", $filename);
		db_query("UPDATE {file_downloads} SET timestamp = %d WHERE filename = '%s'", time(), $filename);
      } 
	  else {
        db_query("INSERT INTO {file_downloads} (filename, count, timestamp) VALUES ('%s', 1,%d)", $filename, time());
	  }			
	} 
	else {
	  $message = t('Failed to download %file', array('%file' => theme('placeholder', $filename))); 	
      watchdog('download', $message, WATCHDOG_WARNING);
	}	
  }
}
/**
 * Implementation of hook_nodeapi()
 */
function download_count_nodeapi(&$node, $op, $teaser) {
  switch ($op) {
    case 'view':
      global $user; 
      if (!$teaser && count($node->files)) {
	    if (user_access('view all downloads count in nodes')) {
		  $node->body = theme('download_count_body', $node);
		}
		else if (user_access('view own nodes downloads count in nodes') && ($node->uid == $user->uid)) {
	  	  $node->body = theme('download_count_body', $node);
		}
	  }
  }
  return;
}
 
function theme_download_count_body($node, $showAll = false) {

  $header[] = array('data' => t('Attachment'));
  $header[] = array('data' => t('Size'));
  $header[] = array('data' => t('Hits'));
  $header[] = array('data' => t('Last download'));
  $rows = array();
  foreach ($node->files as $file) {
    if ($file->list) {
      $href = $file->fid ? file_create_url($file->filepath) : url(file_create_filename($file->filename, file_create_path()));
      $text = $file->description ? $file->description : $file->filename;
	  $pick = db_query("SELECT filename, count, timestamp FROM {file_downloads} WHERE filename = '%s'", $file->filename);
	  if ($attach = db_fetch_object($pick)){
	    $count = $attach->count;
		$last = format_interval(time() - $attach->timestamp) . ' ago';	
	  }
	  else {
	    $count = 0;
		$last = t('Not yet downloaded');
	  }	  
      $rows[] = array(l($text, $href), format_size($file->filesize), $count, $last);
    }
  }
  if (count($rows)) {
    $attachments = theme('table', $header, $rows, array('id' => 'attachments'));
  }

  if (strstr($node->body, '<table')) {
    $startpos = 0;
    $lookagain = true;
    while ($lookagain) {
      if ($pos = strpos ($node->body, '<table', $startpos)) {
        $position = $pos;
        $startpos = $pos + 6;
      } 
	  else {
        $lookagain = false;
      }
    }
   } 
   
    $output = substr_replace($node->body, '', $position);
  
    return $output . $attachments;   
}